<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<Title>GbLib.Kafka</Title>
		<Authors>Sơn Khiếu &amp; Contributors</Authors>
		<Description>The library of Kafka</Description>
		<Version>1.3.0</Version>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Autofac" Version="8.0.0" />
		<PackageReference Include="Confluent.Kafka" Version="2.3.0" />
		<PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.2.0" />
		<PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="8.0.1" />
		<PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.0" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\GbLib.Events\GbLib.Events.csproj" />
	</ItemGroup>

</Project>
