<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.6">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GbLib.Ef.Entities\GbLib.Ef.Entities.csproj" />
    <ProjectReference Include="..\GbLib.Ef.Repositories\GbLib.Ef.Repositories.csproj" />
    <ProjectReference Include="..\GbLib.Ef.Service\GbLib.Ef.Service.csproj" />
    <ProjectReference Include="..\GbLib.Worker\GbLib.Worker.csproj" />
  </ItemGroup>

</Project>
